name = "KnuthBendix"
uuid = "c2604015-7b3d-4a30-8a26-9074551ec60a"
authors = ["Marek Kaluba <kalmar@amu.edu.pl>", "Miko≈Çaj Pabiszczak <mikolaj.pabiszczak@gmail.com>"]
version = "0.5.0"

[deps]
GroupsCore = "d5909c97-4eac-4ecc-a3dc-fdd0858a4120"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
GroupsCore = "0.5.2"
MacroTools = "0.5"
PrecompileTools = "1"
ProgressMeter = "1"
julia = "1.6"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
